name       : guitarix
version    : 0.35.6
release    : 1
source     :
    - https://nchc.dl.sourceforge.net/project/guitarix/guitarix/guitarix2-0.35.6.tar.xz : 81589b6c1a59d0560472ff1054a7fe44fb64344428deacff387f1b09b775db39
license    : GPL-3.0+
component  : multimedia.audio
summary    : GNU/linux Virtual Guitar Amplifier
description: |
    guitarix takes the signal from your guitar as any real amp would do: as a mono-signal from your sound card. The input is processed by a main amp and a rack-section. Both can be routed separately and deliver a processed stereo-signal via Jack. You may fill the rack with effects from more than 25 built-in modules including stuff from a simple noise gate to brain-slashing modulation f/x like flanger, phaser or auto-wah.
    Your signal is processed with minimum latency. On any properly set-up Linux-system you don't have to wait more than 10ms until your sound is processed by guitarix.
libsplit   : no
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(avahi-gobject)
    - pkgconfig(bluez)
    - pkgconfig(eigen3)
    - pkgconfig(fftw3f)
    - pkgconfig(gthread-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtkmm-2.4)
    - pkgconfig(jack)
    - pkgconfig(lilv-0)
    - pkgconfig(lrdf)
    - pkgconfig(raptor2)
    - pkgconfig(sigc++-2.0)
    - pkgconfig(sndfile)
    - gperf
    - ladspa-devel
    - libboost-devel
setup  : |
    ./waf configure --prefix=/usr --install-roboto-font
build  : |
    ./waf build %JOBS%
install : |
    ./waf install --destdir="$installdir"
