name       : guitarix
version    : 0.38.1
release    : 7
source     :
    - https://netcologne.dl.sourceforge.net/project/guitarix/guitarix/guitarix2-0.38.1.tar.xz : 00fda3e1ce1d5f1691665f9ff32bb3c9800381313d49b7c2e25618d0b3ed872f
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : GNU/linux Virtual Guitar Amplifier
description: |
    guitarix takes the signal from your guitar as any real amp would do: as a mono-signal from your sound card. The input is processed by a main amp and a rack-section. Both can be routed separately and deliver a processed stereo-signal via Jack. You may fill the rack with effects from more than 25 built-in modules including stuff from a simple noise gate to brain-slashing modulation f/x like flanger, phaser or auto-wah.
    Your signal is processed with minimum latency. On any properly set-up Linux-system you don't have to wait more than 10ms until your sound is processed by guitarix.
libsplit   : no
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(avahi-gobject)
    - pkgconfig(bluez)
    - pkgconfig(eigen3)
    - pkgconfig(fftw3f)
    - pkgconfig(gthread-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtkmm-2.4)
    - pkgconfig(jack)
    - pkgconfig(libcurl)
    - pkgconfig(lilv-0)
    - pkgconfig(lrdf)
    - pkgconfig(raptor2)
    - pkgconfig(sigc++-2.0)
    - pkgconfig(sndfile)
    - font-roboto-ttf
    - gperf
    - ladspa-devel
    - libboost-devel
    - zita-convolver-devel
    - zita-resampler-devel
rundeps    :
    - font-roboto-ttf
    - jack-audio-connection-kit
setup      : |
    %waf_configure \
        --libdir=%libdir% \
        --fontdir=/usr/share/fonts/truetype/roboto \
        --no-desktop-update \
        --no-ldconfig
build      : |
    %waf_build
install    : |
    %waf_install --libdir=%libdir%
